### PR TITLE
Make sure we only use configured networks

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by Nyholm** [comment]
Ping @nomayann

**Comment by nomayann** [comment]
Hi @Nyholm, what's up?

**Comment by Nyholm** [comment]
Hey!
Would you mind reviewing this PR?

**Comment by nomayann** [comment]
Ok, sorry. I had missed it.

Regards.

**Comment by Nyholm** [comment]
No worries. Thank you for quick feedback.

**Pull request merged**
